version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: almas615/todo-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=root
      - MYSQL_PASS=almas689
      - MYSQL_DB=todo4
    volumes:
      - ./www/:/var/www/html/
    container_name: moe-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=almas689 
      - MYSQL_DATABASE=todo4
    ports:
      - "3306:3306"
    container_name: moe-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend: